# Generated by Django 3.1.1 on 2022-08-27 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kendaraan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('no_hp', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('profil_pic', models.ImageField(blank=True, default='profilepics/avatar.jpg', null=True, upload_to='profilepics')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('unit_kerja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kendaraan.unitkerja')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
