# Generated by Django 3.1.1 on 2022-08-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='profil_pic',
            field=models.ImageField(blank=True, default='profilepics/avatar.jpg', null=True, upload_to='profilepics'),
        ),
    ]
