# Generated by Django 3.1.1 on 2022-08-18 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0007_auto_20220818_0707'),
        ('account', '0002_auto_20220807_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='unit_kerja',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='kendaraan.unitkerja'),
            preserve_default=False,
        ),
    ]
