# Generated by Django 3.1.1 on 2022-08-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220818_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='unit_kerja',
        ),
    ]
