# Generated by Django 3.1.1 on 2022-08-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan.unitkerja')),
            ],
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_polisi', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(choices=[('Sepeda Motor Dinas', 'sepeda motor dinas'), ('Mobil Dinas', 'mobil dinas'), ('Sepeda Motor Pribadi', 'sepeda motor pribadi'), ('Mobil Pribadi', 'mobil pribadi'), ('Bus Jemputan', 'bus jemputan'), ('Ambulans', 'ambulans'), ('Kendaraan Lainnya', 'kendaraan lainnya')], max_length=200)),
                ('warna', models.CharField(choices=[('Abu-abu', 'abu-abu'), ('Biru', 'biru'), ('Coklat', 'coklat'), ('Hitam', 'hitam'), ('Hijau', 'hijau'), ('Merah', 'merah'), ('Putih', 'putih'), ('Kuning', 'kuning'), ('Silver', 'silver'), ('Ungu', 'ungu'), ('Pink', 'pink'), ('Lainnya', 'lainnya')], max_length=200)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='FotoKendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_kendaraan', models.ImageField(blank=True, null=True, upload_to='foto_kendaraan')),
                ('nomor_polisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan.kendaraan')),
            ],
        ),
    ]
