# Generated by Django 3.1.1 on 2022-08-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, default='profilepics/avatar.jpg', null=True, upload_to='foto_pegawai')),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan.unitkerja')),
            ],
        ),
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_polisi', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(choices=[('Sepeda Motor Dinas', 'Sepeda Motor Dinas'), ('Mobil Dinas', 'Mobil Dinas'), ('Sepeda Motor Pribadi', 'Sepeda Motor Pribadi'), ('Mobil Pribadi', 'Mobil Pribadi'), ('Bus Jemputan', 'Bus Jemputan'), ('Ambulans', 'Ambulans'), ('Kendaraan Lainnya', 'Kendaraan Lainnya')], max_length=200)),
                ('warna', models.CharField(choices=[('Hitam', 'Hitam'), ('Silver', 'Silver'), ('Putih', 'Putih'), ('Abu-abu', 'Abu-Abu'), ('Biru', 'Biru'), ('Coklat', 'Coklat'), ('Hijau', 'Hijau'), ('Merah', 'Merah'), ('Kuning', 'Kuning'), ('Lainnya', 'Lainnya')], max_length=200)),
                ('merk_type', models.CharField(blank=True, max_length=300, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='FotoKendaraan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_kendaraan', models.ImageField(blank=True, null=True, upload_to='foto_kendaraan')),
                ('nomor_polisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kendaraan.kendaraan')),
            ],
        ),
    ]
