# Generated by Django 3.1.1 on 2022-08-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_pegawai'),
        ),
    ]
