# Generated by Django 3.1.1 on 2022-08-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0003_auto_20220807_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='kendaraan',
            name='merk_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
