# Generated by Django 3.1.1 on 2022-08-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraan', '0006_kendaraan_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendaraan',
            name='jenis_kendaraan',
            field=models.CharField(choices=[('Sepeda Motor Dinas', 'Sepeda Motor Dinas'), ('Mobil Dinas', 'Mobil Dinas'), ('Sepeda Motor Pribadi', 'Sepeda Motor Pribadi'), ('Mobil Pribadi', 'Mobil Pribadi'), ('Bus Jemputan', 'Bus Jemputan'), ('Ambulans', 'Ambulans'), ('Kendaraan Lainnya', 'Kendaraan Lainnya')], max_length=200),
        ),
        migrations.AlterField(
            model_name='kendaraan',
            name='warna',
            field=models.CharField(choices=[('Abu-abu', 'Abu-Abu'), ('Biru', 'Biru'), ('Coklat', 'Coklat'), ('Hitam', 'Hitam'), ('Hijau', 'Hijau'), ('Merah', 'Merah'), ('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Silver', 'Silver'), ('Lainnya', 'Lainnya')], max_length=200),
        ),
    ]
